config/routes.rb
Rails.application.routes.draw do
  with_dev_auth = lambda do |app|
    if ENV["ADMIN_USERNAME"].present?
      Rack::Builder.new do
        use Rack::Auth::Basic do |username, password|
          # NOTE: Yes, we use & instead of &&. This is to protect against timing attacks. & needs to evaluate both arguments, while && will may only evaluate one.
          ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV.fetch("ADMIN_USERNAME"))) &
            ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV.fetch("ADMIN_PASSWORD")))
        end

        run app
      end
    else
      app
    end
  end

  mount Avo::Engine, at: Avo.configuration.root_path
  mount with_dev_auth[GoodJob::Engine], at: "/good_job"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  get "registrations/:season_slug", to: "registrations#index", as: :registrations
  get "registrations/:event_slug/new", to: "registrations#new", as: :new_registration
  post "registrations/:event_slug", to: "registrations#create", as: :create_registration
  get "metrics/:season_slug", to: "metrics#show", as: :metrics
  get ":season_slug", to: "attendances#root", as: :root_attendances
  get "attendances/:event_slug", to: "attendances#index", as: :attendances
  post "attendances", to: "attendances#create", as: :create_attendance
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  include Slugify

  belongs_to :event
  validates :person_name, presence: true, length: {in: 1..200}

  def self.ransackable_attributes(auth_object = nil)
    %w[person_name id]
  end

  def self.ransackable_associations(*)
    []
  end

  def branch_name = BRANCH_NAMES.invert.fetch(branch)

  def attended? = attended_at.present?
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def root
    @season = Season.includes(events: {registrations: {}, attendances: {}})
      .find_by!(slug: params[:season_slug])
    @events = @season.events
      .where(start_at: ActiveSupport::TimeZone["America/Montreal"].now.change(hour: 4)..).order(:start_at)
      .to_a
    render
  end

  def index
    @event = Event.find_by!(slug: params[:event_slug])
    @people = @event.registrations.includes(:attendance).index_by(&:person_name)
      .merge(@event.attendances.index_by(&:person_name))
      .values
    render
  end

  def create
    @event = Event.find_by!(slug: params[:event_slug])
    if (registration_slug = params[:registration_slug]).present?
      @event.record_attendance!(registration_slug)
    elsif (attendance_slug = params[:attendance_slug]).present?
      @event.flip_attendance!(attendance_slug)
    elsif (person_name = params[:person_name]).present? && (branch = params[:branch]).present?
      @event.record_new_attendance!(person_name:, branch:)
    end

    redirect_to attendances_path(@event.slug)
  end
end

app/controllers/avo/attendances_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
class Avo::AttendancesController < Avo::ResourcesController
end

app/views/attendances/index.html.erb
<h1><%= @event.title %> <%= l @event.start_at, format: :hour_minute %></h1>

<div class="mb-2">
  <%= link_to "⬅️ Retour à la liste", root_attendances_path(@event.season.slug) %>
</div>

<table class="table table-hover">
  <thead>
  </thead>
  <tbody>
    <% @people.sort_by { _1.person_name.downcase }.each do |person| %>
      <tr>
        <td><%= person.person_name %></td>
        <td><%= person.branch_name %></td>
        <td>
          <% if !person.attended? %>
            <%= form_tag create_attendance_path, method: :post do %>
              <%= hidden_field_tag :event_slug, @event.slug %>
              <%= hidden_field_tag :registration_slug, person.slug if person.kind_of?(Registration) %>
              <%= hidden_field_tag :attendance_slug, person.slug if person.kind_of?(Attendance) %>
              <%= submit_tag "Présent", class: "btn btn-primary w-50" %>
            <% end %>
          <% end %>

          <% if person.attended? %>
            <%= form_tag create_attendance_path, method: :post do %>
              <%= hidden_field_tag :event_slug, @event.slug %>
              <%= hidden_field_tag :registration_slug, person.slug if person.kind_of?(Registration) %>
              <%= hidden_field_tag :attendance_slug, person.slug if person.kind_of?(Attendance) %>
              <%= submit_tag "Absent", class: "btn btn-warning w-50" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="card text-bg-light">
  <div class="card-body">
    <h5 class="card-title">Nouvelle inscription</h5>

    <%= form_tag create_attendance_path, method: :post do %>
      <%= hidden_field_tag :event_slug, @event.slug %>

      <div class="mb-2">
        <%= label_tag :person_name, "Nom de l'enfant:", class: "form-label" %>
        <%= text_field_tag :person_name, nil, class: "form-control" %>
      </div>

      <div class="mt-2">
        <%= label_tag :branch, "Unité de l'enfant:", class: "form-label" %>
        <%= select_tag :branch, options_for_select(BRANCH_NAMES), class: "form-select" %>
      </div>

      <%= submit_tag "Enregistrer", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="my-2">
  <%= link_to "⬅️ Retour à la liste", root_attendances_path(@event.season.slug) %>
</div>

app/views/attendances/root.html.erb
<h1>Présences <%= @season.name %></h1>
<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to attendances_path(event.slug) do %>
        <%= event.title %> <%= l event.start_at, format: :day_month %> <%= l event.start_at, format: :hour_minute %>
      <% end %>

      <%= event.attended_count %> / <%= event.registered_count %>
    </li>
  <% end %>
</ul>